version: "3"
services:
  knic-jupyter:
    image: docker-reg.ads.isi.edu:443/knic-jupyter
    command: sh -c "jupyter lab --port 5644 --no-browser --ip='*' --NotebookApp.token='' --NotebookApp.password='' --allow-root"
    container_name: knic-jupyter
    restart: always
    ports:
      - "5644:5644"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
